basePath: /v1
definitions:
  entitys.TransactionEntity:
    properties:
      description:
        type: string
      id:
        type: string
      purchase_amount:
        type: number
      transaction_date:
        type: string
    type: object
  usecases.StoreTransactionInput:
    properties:
      description:
        type: string
      purchase_amount:
        type: number
      transaction_date:
        type: string
    type: object
host: localhost:5000
info:
  contact:
    name: Isac Arcanjo
    url: https://github.com/isacarcanjo
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Purchase Transaction API Docs
  version: 1.0.0
paths:
  /transaction:
    post:
      consumes:
      - application/json
      description: Create transaction
      parameters:
      - description: Transaction
        in: body
        name: transaction
        required: true
        schema:
          $ref: '#/definitions/usecases.StoreTransactionInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entitys.TransactionEntity'
      tags:
      - transaction
  /transaction/{id}:
    get:
      consumes:
      - application/json
      description: Get transaction
      parameters:
      - description: Id transaction
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entitys.TransactionEntity'
      tags:
      - transaction
swagger: "2.0"
